[2024-09-13 10:40:49 +0000] [32300] [DEBUG] Current configuration:
  config: gunicorn_conf.py
  wsgi_app: None
  bind: ['unix:/projects/auth_module/gunicorn.sock']
  backlog: 2048
  workers: 5
  worker_class: uvicorn.workers.UvicornWorker
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /projects/auth_module
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 1000
  group: 33
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1', '::1']
  accesslog: /projects/auth_module/access_log
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: /projects/auth_module/error_log
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  logconfig_json: None
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: app.main:app
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7e426840fba0>
  on_reload: <function OnReload.on_reload at 0x7e426840fce0>
  when_ready: <function WhenReady.when_ready at 0x7e426840fe20>
  pre_fork: <function Prefork.pre_fork at 0x7e4268430040>
  post_fork: <function Postfork.post_fork at 0x7e4268430180>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7e42684302c0>
  worker_int: <function WorkerInt.worker_int at 0x7e4268430400>
  worker_abort: <function WorkerAbort.worker_abort at 0x7e4268430540>
  pre_exec: <function PreExec.pre_exec at 0x7e4268430680>
  pre_request: <function PreRequest.pre_request at 0x7e42684307c0>
  post_request: <function PostRequest.post_request at 0x7e4268430860>
  child_exit: <function ChildExit.child_exit at 0x7e42684309a0>
  worker_exit: <function WorkerExit.worker_exit at 0x7e4268430ae0>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7e4268430c20>
  on_exit: <function OnExit.on_exit at 0x7e4268430d60>
  ssl_context: <function NewSSLContext.ssl_context at 0x7e4268430f40>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1', '::1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  permit_obsolete_folding: False
  strip_header_spaces: False
  permit_unconventional_http_method: False
  permit_unconventional_http_version: False
  casefold_http_method: False
  forwarder_headers: ['SCRIPT_NAME', 'PATH_INFO']
  header_map: drop
[2024-09-13 10:40:49 +0000] [32300] [INFO] Starting gunicorn 23.0.0
[2024-09-13 10:40:49 +0000] [32300] [DEBUG] Arbiter booted
[2024-09-13 10:40:49 +0000] [32300] [INFO] Listening at: unix:/projects/auth_module/gunicorn.sock (32300)
[2024-09-13 10:40:49 +0000] [32300] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2024-09-13 10:40:49 +0000] [32301] [INFO] Booting worker with pid: 32301
[2024-09-13 10:40:49 +0000] [32302] [INFO] Booting worker with pid: 32302
[2024-09-13 10:40:49 +0000] [32303] [INFO] Booting worker with pid: 32303
[2024-09-13 10:40:49 +0000] [32304] [INFO] Booting worker with pid: 32304
[2024-09-13 10:40:49 +0000] [32305] [INFO] Booting worker with pid: 32305
[2024-09-13 10:40:49 +0000] [32300] [DEBUG] 5 workers
[2024-09-13 10:40:49 +0000] [32301] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/projects/auth_module/venv/lib/python3.12/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
    worker.init_process()
  File "/projects/auth_module/venv/lib/python3.12/site-packages/uvicorn/workers.py", line 75, in init_process
    super().init_process()
  File "/projects/auth_module/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
  File "/projects/auth_module/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/projects/auth_module/venv/lib/python3.12/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/projects/auth_module/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/projects/auth_module/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/projects/auth_module/venv/lib/python3.12/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/projects/auth_module/app/main.py", line 4, in <module>
    from db.session import engine, Base
ModuleNotFoundError: No module named 'db'
[2024-09-13 10:40:49 +0000] [32301] [INFO] Worker exiting (pid: 32301)
[2024-09-13 10:40:49 +0000] [32300] [ERROR] Worker (pid:32301) exited with code 3
[2024-09-13 10:40:49 +0000] [32300] [ERROR] Worker (pid:32305) was sent SIGTERM!
[2024-09-13 10:40:49 +0000] [32300] [ERROR] Worker (pid:32303) was sent SIGTERM!
[2024-09-13 10:40:49 +0000] [32300] [ERROR] Worker (pid:32304) was sent SIGTERM!
[2024-09-13 10:40:49 +0000] [32300] [ERROR] Worker (pid:32302) was sent SIGTERM!
[2024-09-13 10:40:50 +0000] [32300] [ERROR] Shutting down: Master
[2024-09-13 10:40:50 +0000] [32300] [ERROR] Reason: Worker failed to boot.
[2024-09-13 11:08:30 +0000] [37972] [DEBUG] Current configuration:
  config: gunicorn_conf.py
  wsgi_app: None
  bind: ['unix:/projects/auth_module/gunicorn.sock']
  backlog: 2048
  workers: 5
  worker_class: uvicorn.workers.UvicornWorker
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /projects/auth_module
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 1000
  group: 33
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1', '::1']
  accesslog: /projects/auth_module/access_log
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: /projects/auth_module/error_log
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  logconfig_json: None
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: app.main:app
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7f99b5b67ba0>
  on_reload: <function OnReload.on_reload at 0x7f99b5b67ce0>
  when_ready: <function WhenReady.when_ready at 0x7f99b5b67e20>
  pre_fork: <function Prefork.pre_fork at 0x7f99b5b88040>
  post_fork: <function Postfork.post_fork at 0x7f99b5b88180>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7f99b5b882c0>
  worker_int: <function WorkerInt.worker_int at 0x7f99b5b88400>
  worker_abort: <function WorkerAbort.worker_abort at 0x7f99b5b88540>
  pre_exec: <function PreExec.pre_exec at 0x7f99b5b88680>
  pre_request: <function PreRequest.pre_request at 0x7f99b5b887c0>
  post_request: <function PostRequest.post_request at 0x7f99b5b88860>
  child_exit: <function ChildExit.child_exit at 0x7f99b5b889a0>
  worker_exit: <function WorkerExit.worker_exit at 0x7f99b5b88ae0>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7f99b5b88c20>
  on_exit: <function OnExit.on_exit at 0x7f99b5b88d60>
  ssl_context: <function NewSSLContext.ssl_context at 0x7f99b5b88f40>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1', '::1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  permit_obsolete_folding: False
  strip_header_spaces: False
  permit_unconventional_http_method: False
  permit_unconventional_http_version: False
  casefold_http_method: False
  forwarder_headers: ['SCRIPT_NAME', 'PATH_INFO']
  header_map: drop
[2024-09-13 11:08:30 +0000] [37972] [INFO] Starting gunicorn 23.0.0
[2024-09-13 11:08:30 +0000] [37972] [DEBUG] Arbiter booted
[2024-09-13 11:08:30 +0000] [37972] [INFO] Listening at: unix:/projects/auth_module/gunicorn.sock (37972)
[2024-09-13 11:08:30 +0000] [37972] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2024-09-13 11:08:30 +0000] [37973] [INFO] Booting worker with pid: 37973
[2024-09-13 11:08:30 +0000] [37974] [INFO] Booting worker with pid: 37974
[2024-09-13 11:08:30 +0000] [37975] [INFO] Booting worker with pid: 37975
[2024-09-13 11:08:30 +0000] [37976] [INFO] Booting worker with pid: 37976
[2024-09-13 11:08:30 +0000] [37977] [INFO] Booting worker with pid: 37977
[2024-09-13 11:08:30 +0000] [37972] [DEBUG] 5 workers
[2024-09-13 11:08:31 +0000] [37974] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/projects/auth_module/venv/lib/python3.12/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
    worker.init_process()
  File "/projects/auth_module/venv/lib/python3.12/site-packages/uvicorn/workers.py", line 75, in init_process
    super().init_process()
  File "/projects/auth_module/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
  File "/projects/auth_module/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/projects/auth_module/venv/lib/python3.12/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/projects/auth_module/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/projects/auth_module/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/projects/auth_module/venv/lib/python3.12/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/projects/auth_module/app/main.py", line 4, in <module>
    from db.session import engine, Base
ModuleNotFoundError: No module named 'db'
[2024-09-13 11:08:31 +0000] [37974] [INFO] Worker exiting (pid: 37974)
[2024-09-13 11:08:31 +0000] [37975] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/projects/auth_module/venv/lib/python3.12/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
    worker.init_process()
  File "/projects/auth_module/venv/lib/python3.12/site-packages/uvicorn/workers.py", line 75, in init_process
    super().init_process()
  File "/projects/auth_module/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
  File "/projects/auth_module/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/projects/auth_module/venv/lib/python3.12/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/projects/auth_module/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/projects/auth_module/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/projects/auth_module/venv/lib/python3.12/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/projects/auth_module/app/main.py", line 4, in <module>
    from db.session import engine, Base
ModuleNotFoundError: No module named 'db'
[2024-09-13 11:08:31 +0000] [37975] [INFO] Worker exiting (pid: 37975)
[2024-09-13 11:08:31 +0000] [37972] [ERROR] Worker (pid:37974) exited with code 3
[2024-09-13 11:08:31 +0000] [37972] [ERROR] Worker (pid:37976) was sent SIGTERM!
[2024-09-13 11:08:31 +0000] [37972] [ERROR] Worker (pid:37977) was sent SIGTERM!
[2024-09-13 11:08:31 +0000] [37972] [ERROR] Worker (pid:37973) was sent SIGTERM!
[2024-09-13 11:08:31 +0000] [37972] [ERROR] Worker (pid:37975) was sent SIGTERM!
[2024-09-13 11:08:31 +0000] [37972] [ERROR] Shutting down: Master
[2024-09-13 11:08:31 +0000] [37972] [ERROR] Reason: Worker failed to boot.
[2024-09-13 11:10:42 +0000] [38595] [DEBUG] Current configuration:
  config: gunicorn_conf.py
  wsgi_app: None
  bind: ['unix:/projects/auth_module/gunicorn.sock']
  backlog: 2048
  workers: 5
  worker_class: uvicorn.workers.UvicornWorker
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /projects/auth_module
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 1000
  group: 33
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1', '::1']
  accesslog: /projects/auth_module/access_log
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: /projects/auth_module/error_log
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  logconfig_json: None
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: main:app
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x703584a97ba0>
  on_reload: <function OnReload.on_reload at 0x703584a97ce0>
  when_ready: <function WhenReady.when_ready at 0x703584a97e20>
  pre_fork: <function Prefork.pre_fork at 0x703584ab4040>
  post_fork: <function Postfork.post_fork at 0x703584ab4180>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x703584ab42c0>
  worker_int: <function WorkerInt.worker_int at 0x703584ab4400>
  worker_abort: <function WorkerAbort.worker_abort at 0x703584ab4540>
  pre_exec: <function PreExec.pre_exec at 0x703584ab4680>
  pre_request: <function PreRequest.pre_request at 0x703584ab47c0>
  post_request: <function PostRequest.post_request at 0x703584ab4860>
  child_exit: <function ChildExit.child_exit at 0x703584ab49a0>
  worker_exit: <function WorkerExit.worker_exit at 0x703584ab4ae0>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x703584ab4c20>
  on_exit: <function OnExit.on_exit at 0x703584ab4d60>
  ssl_context: <function NewSSLContext.ssl_context at 0x703584ab4f40>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1', '::1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  permit_obsolete_folding: False
  strip_header_spaces: False
  permit_unconventional_http_method: False
  permit_unconventional_http_version: False
  casefold_http_method: False
  forwarder_headers: ['SCRIPT_NAME', 'PATH_INFO']
  header_map: drop
[2024-09-13 11:10:42 +0000] [38595] [INFO] Starting gunicorn 23.0.0
[2024-09-13 11:10:42 +0000] [38595] [DEBUG] Arbiter booted
[2024-09-13 11:10:42 +0000] [38595] [INFO] Listening at: unix:/projects/auth_module/gunicorn.sock (38595)
[2024-09-13 11:10:42 +0000] [38595] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2024-09-13 11:10:42 +0000] [38596] [INFO] Booting worker with pid: 38596
[2024-09-13 11:10:42 +0000] [38596] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/projects/auth_module/venv/lib/python3.12/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
    worker.init_process()
  File "/projects/auth_module/venv/lib/python3.12/site-packages/uvicorn/workers.py", line 75, in init_process
    super().init_process()
  File "/projects/auth_module/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
  File "/projects/auth_module/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/projects/auth_module/venv/lib/python3.12/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/projects/auth_module/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/projects/auth_module/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/projects/auth_module/venv/lib/python3.12/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'main'
[2024-09-13 11:10:42 +0000] [38596] [INFO] Worker exiting (pid: 38596)
[2024-09-13 11:10:42 +0000] [38597] [INFO] Booting worker with pid: 38597
[2024-09-13 11:10:42 +0000] [38597] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/projects/auth_module/venv/lib/python3.12/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
    worker.init_process()
  File "/projects/auth_module/venv/lib/python3.12/site-packages/uvicorn/workers.py", line 75, in init_process
    super().init_process()
  File "/projects/auth_module/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
  File "/projects/auth_module/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/projects/auth_module/venv/lib/python3.12/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/projects/auth_module/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/projects/auth_module/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/projects/auth_module/venv/lib/python3.12/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'main'
[2024-09-13 11:10:42 +0000] [38597] [INFO] Worker exiting (pid: 38597)
[2024-09-13 11:10:42 +0000] [38595] [ERROR] Worker (pid:38596) exited with code 3
[2024-09-13 11:10:42 +0000] [38595] [ERROR] Worker (pid:38597) was sent SIGTERM!
[2024-09-13 11:10:42 +0000] [38595] [ERROR] Shutting down: Master
[2024-09-13 11:10:42 +0000] [38595] [ERROR] Reason: Worker failed to boot.
